# Generated by Django 4.1 on 2022-08-15 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_image_alter_project_video'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ['-date_added']},
        ),
    ]
